# Generated by Django 5.0.7 on 2024-07-09 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_advert'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advert',
            new_name='Templates',
        ),
    ]
