# Generated by Django 5.0.7 on 2024-07-09 20:22

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_advert_templates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templates',
            old_name='text',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='templates',
            name='url',
        ),
        migrations.AddField(
            model_name='templates',
            name='content',
            field=wagtail.fields.RichTextField(default='hi'),
            preserve_default=False,
        ),
    ]
