# Generated by Django 5.0.7 on 2024-07-09 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_text_templates_title_remove_templates_url_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='Template',
        ),
    ]
